// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UTSAfida.Data;

namespace UTSAfida.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220203074111_tb_jadwal")]
    partial class tb_jadwal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("UTSAfida.Models.Jadwal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Keterangan")
                        .HasColumnType("text");

                    b.Property<DateTime>("TglMulai")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("TglSelesai")
                        .HasColumnType("datetime");

                    b.Property<string>("Tutor")
                        .HasColumnType("text");

                    b.Property<string>("pelatihan")
                        .HasColumnType("text");

                    b.Property<string>("pertemuan")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tb_Jadwal");
                });

            modelBuilder.Entity("UTSAfida.Models.Roles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tb_Roles");
                });

            modelBuilder.Entity("UTSAfida.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("RolesId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Username");

                    b.HasIndex("RolesId");

                    b.ToTable("Tb_User");
                });

            modelBuilder.Entity("UTSAfida.Models.User", b =>
                {
                    b.HasOne("UTSAfida.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesId");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
